name: "React Ci Pipeline / Workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: "Setting up Node js"
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: "Checkout Repository"
        uses: actions/checkout@v5


      - name: "Installing Dependencies"
        run: npm install


      - name: "Build"
        run: npm run build

      - name: "Uploading Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: 'Build'
          path: dist