name: "React Ci Pipeline / Workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: "Setting up Node js"
        uses: actions/setup-node@v5
        with:
          node-version: '21'

      - name: "Checkout Repository"
        uses: actions/checkout@v5


      - name: "Installing Dependencies"
        run: npm install
